# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Codes/Verilog/fft_block/fft_block.srcs/sources_1/ip/FFT/FFT.xci
# IP: The module: 'FFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Codes/Verilog/fft_block/fft_block.gen/sources_1/ip/FFT/FFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Codes/Verilog/fft_block/fft_block.srcs/sources_1/ip/FFT/FFT.xci
# IP: The module: 'FFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Codes/Verilog/fft_block/fft_block.gen/sources_1/ip/FFT/FFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
